### DISCUSSION TITLE
Accessing a private API Gateway via Basti

### DISCUSSION THREAD

**Discussion by danielbollom** [BohdanPetryshyn/basti#106] [Q&A] [answered]
Hey there! I've been trying out Basti for connecting to RDS resources in a VPC over the last few days and it's been super easy to get up and running which has been awesome.

I've hit some issues with trying to set up a custom resource though, in this case a private API Gateway that lives in a VPC. 

Two questions if you have a few minutes:
1. Should this be possible to get set up using custom resources?
2. If so, would a config like below be correct or is something missing?

```
  api-gw:
    target:
      customTargetVpc: <vpc id>
      customTargetHost: <api gateway domain>
      customTargetPort: 443
    localPort: 8080
```

Thanks so much!
